/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class FizzTest {
	
    @Test 
	public void firstTest() {
        FizzBuzz buzz = new FizzBuzz();
        assertEquals("hey", buzz.check("hey"));
    }
}
